version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  ecspresso: fujiwara/ecspresso@0.0.10

executors:
  ecspresso_build_and_deploy:
    docker:
      - image: cimg/base:2020.08
    working_directory: ~/project/firelens-playground

commands:
  setup_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
  build-and-push-image:
    parameters:
      image-name:
        type: string
    steps:
      - run:
          name: Build << parameters.image-name >> image
          command: |
            cd docker/<< parameters.image-name >>
            docker build . -t "${ECR_URI}"/<< parameters.image-name >>:"${CIRCLE_SHA1}"
      - run:
          name: Push << parameters.image-name >> image
          command: |
            aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${ECR_URI}"
            docker push "${ECR_URI}"/<< parameters.image-name >>:"${CIRCLE_SHA1}"

jobs:
  build:
    executor: ecspresso_build_and_deploy
    steps:
      - checkout
      - setup_docker
      - aws-cli/setup
      - build-and-push-image:
          image-name: firelens-sample
      - build-and-push-image:
          image-name: fluentd

  deploy:
    executor: ecspresso_build_and_deploy
    steps:
      - checkout
      - ecspresso/install:
          version: v0.17.3
      - run:
          command: |
            ecspresso register --config config.yaml

workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - deploy:
          requires:
            - build

