version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  ecspresso: fujiwara/ecspresso@0.0.10

executors:
  ecspresso_build_and_deploy:
    docker:
      - image: cimg/base:2020.08
    working_directory: ~/project/firelens-playground

commands:
  setup_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3

jobs:
  build:
    executor: ecspresso_build_and_deploy
    steps:
      - checkout
      - setup_docker
      - run:
          name: Build App
          command: |
            cd docker/app
            docker build . -t "${ECR_URI}"/firelens-sample:"${CIRCLE_SHA1}"
      - aws-cli/setup
      - run:
          name: Push image
          command: |
            aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${ECR_URI}"
            docker push "${ECR_URI}"/firelens-sample:"${CIRCLE_SHA1}"
  deploy:
    executor: ecspresso_build_and_deploy
    steps:
      - checkout
      - ecspresso/install:
          version: v0.17.3
      - run:
          command: |
            ecspresso register --config config.yaml

workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - deploy:
          requires:
            - build

